[package]
name = "tracing-gstreamer"
version = "0.1.1"
edition = "2018"
authors = ["Simonas Kazlauskas <tracing-gstreamer@kazlauskas.me>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/standard-ai/tracing-gstreamer"
documentation = "https://docs.rs/tracing-gstreamer/"
readme = "README.mkd"
description = "Bridge between gstreamer and the tracing ecosystem"
keywords = ["tracing", "logging", "gstreamer", "multimedia"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[lib]
harness = false

[dependencies]
libc = "0.2"
once_cell = "1.8"
tracing-core = "0.1"

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
gstreamer = "0.17"
glib = "0.14"
tracing = "0.1"
tracing-subscriber = "0.2"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "tracing_gstreamer_docs"]
