[package]
name = "tracing-gstreamer"
version = "0.1.0"
edition = "2018"
authors = ["Simonas Kazlauskas <tracing-gstreamer@kazlauskas.me>"]
license = "MIT OR Apache-2.0"

[lib]
harness = false

[dependencies]
libc = "0.2"
once_cell = "1.8"
tracing-core = "0.1"

[dev-dependencies]
gstreamer = "0.17"
glib = "0.14"
tracing = "0.1"
